= Check Published RAML API Specifications Starting Soon

As of ..., the API editor in Design Center is more precise in ensuring that the RAML in your API specifications is valid. However, it is possible that one or more of the APIs that you used previous versions of the API editor to create and publish to Anypoint Exchange includes invalid RAML that those previous versions did not flag.

Check your published APIs by opening them in the API editor in Design Center. You can use the guide on on xref:design-center::design-modify-raml-specs-conform.adoc[this page] to correct a number of errors that MuleSoft has found while testing the changes to the API editor on a large number of RAML API specifications. If you see errors that this guide does not include, refer to the specifications for RAML 0.8 and 1.0, which you can read on https://raml.org/[raml.org].

You have a grace period of at least one year to correct any invalid RAML that your published API specifications might include. After the grace period expires, you will be unable to republish and redeploy APIs in which there is invalid RAML.
